pipeline {
  agent any

  stages {
    stage('Remove Duplicate Partner Blocks') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: 'main']],
                  userRemoteConfigs: [[url: 'https://github.com/Ayzazkhan/Godady-digilaxy-partner-page-automation.git']]])

        withCredentials([
          string(credentialsId: 'ftp-academiccoursehelp.com', variable: 'FTP_PASS_ACADEMICCOURSEHELP_COM'),
          string(credentialsId: 'ftp-assignmenteducators.co.uk', variable: 'FTP_PASS_ASSIGNMENTEDUCATORS_CO_UK')
        ]) {
          sh 'python3 duplication/cleanup_duplicates.py'
        }
      }
    }
  }
}
